default_stages: [ "commit", "commit-msg", "push" ]
default_language_version:
  python: python3.10
exclude: static
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: "Code formatter"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
        name: "End of file fixer"
      - id: debug-statements
        name: "Debug imports and breakpoints checker"
      - id: requirements-txt-fixer
        name: "Requirements txt fixer"
      - id: mixed-line-ending
        name: "Mixed line ending fixer"
      - id: check-yaml
        name: "Yaml checker"
        args: [ '--unsafe' ]
      - id: trailing-whitespace
        name: "Trailing whitespace fixer"

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: "Linter"
        args:
          - --config=setup.cfg
        additional_dependencies:
          - pep8-naming
          - flake8-builtins
          - flake8-comprehensions
          - flake8-bugbear
          - flake8-pytest-style
          - flake8-cognitive-complexity

  - repo: local
    hooks:
      - id: mypy
        name: "Static type checker"
        entry: mypy sebulba/
        language: system
        types: [ python ]
        pass_filenames: false

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint
        name: "Commit linter"
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]
